version: '3'
services:
  pulsar:
    image: apachepulsar/pulsar-all
    container_name: pulsar
    ports:
      - "8080:8080"
      - "6650:6650"
    command: ["bin/pulsar", "standalone"]
    restart: unless-stopped
  sql-client:
    build: ./client-image
    image: demo/pulsar-flink-sql
    container_name: pulsar-flink-sql-client
    depends_on:
      - pulsar
      - jobmanager
    environment:
      FLINK_JOBMANAGER_HOST: jobmanager
  jobmanager:
    image: flink:1.12.1-scala_2.11
    container_name: pulsar-flink-sql-jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
  taskmanager:
    image: flink:1.12.1-scala_2.11
    container_name: pulsar-flink-sql-taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager